# Generated by Django 5.2.6 on 2025-09-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('FIXA', 'fixa'), ('VARIAVEL', 'variável'), ('IMPOSTO', 'imposto'), ('RENDIMENTOS', 'rendimentos')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18)),
                ('tipo', models.CharField(choices=[('ASSOCIADO', 'Associado'), ('CLIENTE', 'Cliente'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor'), ('SOCIO', 'Sócio'), ('OUTRO', 'Outro')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('A VISTA', 'À Vista'), ('CARTÃO', 'Cartão'), ('PIX', 'Pix'), ('BOLETO', 'Boleto')], max_length=10)),
                ('categoriaNome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.categoria')),
                ('contatoNome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.contato')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('A VISTA', 'À Vista'), ('CARTÃO', 'Cartão'), ('PIX', 'Pix'), ('BOLETO', 'Boleto')], max_length=10)),
                ('categoriaNome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.categoria')),
                ('contatoNome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.contato')),
            ],
        ),
    ]
