# Generated by Django 5.2.6 on 2025-10-21 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('FIXA', 'Fixa'), ('VARIAVEL', 'Variável'), ('IMPOSTO', 'Imposto'), ('RENDIMENTOS', 'Rendimentos')], max_length=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('tipo', models.CharField(choices=[('ASSOCIADO', 'Associado'), ('CLIENTE', 'Cliente'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor'), ('SOCIO', 'Sócio'), ('OUTRO', 'Outro')], max_length=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('AVISTA', 'À Vista'), ('CARTÃO', 'Cartão'), ('PIX', 'Pix'), ('BOLETO', 'Boleto')], max_length=10)),
                ('categoriaNome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.categoria', verbose_name='Categoria')),
                ('contatoNome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.contato', verbose_name='Contato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('AVISTA', 'À Vista'), ('CARTÃO', 'Cartão'), ('PIX', 'Pix'), ('BOLETO', 'Boleto')], max_length=10)),
                ('categoriaNome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.categoria', verbose_name='Categoria')),
                ('contatoNome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.contato', verbose_name='Contato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
