# Generated by Django 5.2.6 on 2025-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('FIXA', 'Fixa'), ('VARIAVEL', 'Variável'), ('IMPOSTO', 'Imposto'), ('RENDIMENTOS', 'Rendimentos')], max_length=12),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
